package za.co.fraudruleengine.infrastructure.persistence.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing a persisted financial transaction in the {@code transactions} table.
 *
 * <p>This entity serves dual purposes:
 * <ol>
 *   <li><strong>Input record</strong> — every transaction submitted to the API is persisted before
 *       evaluation, ensuring a complete audit trail regardless of whether fraud is detected.</li>
 *   <li><strong>Evaluation result</strong> — after rule evaluation, {@code riskScore} and
 *       {@code fraudulent} are written back, turning the record into a queryable outcome.</li>
 * </ol>
 *
 * <p>The primary key ({@code id}) is a client-supplied UUID generated in
 * {@link za.co.fraudruleengine.application.FraudEvaluationService} before the first save,
 * allowing the ID to be used in log messages and the domain model before the entity is flushed
 * to the database.
 *
 * <p>Lombok's {@code @Builder}, {@code @Getter}, and {@code @Setter} are used throughout; no
 * manual constructor or accessor boilerplate is present. {@code @NoArgsConstructor} is required
 * by the JPA specification.
 */
@Entity
@Table(name = "transactions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TransactionEntity {

    /** Unique identifier assigned at ingestion time; not generated by the database. */
    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;

    /** The customer account that originated the transaction. */
    @Column(name = "account_id", nullable = false)
    private String accountId;

    /** Transaction amount; stored with up to 4 decimal places for monetary precision. */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    /** ISO 4217 currency code, maximum 3 characters (e.g. {@code "ZAR"}, {@code "USD"}). */
    @Column(nullable = false, length = 3)
    private String currency;

    /** Human-readable name of the receiving merchant. */
    @Column(name = "merchant_name", nullable = false)
    private String merchantName;

    /** Merchant category code (MCC) or classification string; optional. */
    @Column(name = "merchant_category")
    private String merchantCategory;

    /** Originating channel (e.g. {@code "ONLINE"}, {@code "POS"}, {@code "ATM"}). */
    @Column(nullable = false, length = 20)
    private String channel;

    /** ISO 3166-1 alpha-3 country code of the transaction (e.g. {@code "ZAF"}); optional. */
    @Column(name = "country_code", length = 3)
    private String countryCode;

    /** The moment the transaction occurred, as reported by the submitting system. */
    @Column(name = "transaction_time", nullable = false)
    private LocalDateTime transactionTime;

    /**
     * The aggregate risk score computed by the rule engine.
     * Defaults to {@code 0} before evaluation; written back after rule execution.
     */
    @Column(name = "risk_score")
    private int riskScore;

    /**
     * Whether the rule engine classified this transaction as fraudulent.
     * {@code true} when {@code riskScore >= fraud.score.threshold}; {@code false} otherwise.
     */
    @Column(name = "is_fraudulent", nullable = false)
    private boolean fraudulent;

    /**
     * Timestamp set automatically by Hibernate on first insert.
     * Not updated on subsequent saves ({@code updatable = false}).
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
