package za.co.fraudruleengine.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import za.co.fraudruleengine.model.AlertStatus;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity representing a fraud alert raised when a transaction's aggregate risk score meets
 * or exceeds the configured threshold.
 *
 * <p>Alerts are created by {@link za.co.fraudruleengine.service.FraudEvaluationService} and
 * managed (queried and status-updated) by {@link za.co.fraudruleengine.service.AlertQueryService}.
 * Each alert is linked to the originating transaction via {@code transactionId} (a foreign-key
 * reference by UUID rather than a JPA association, to keep the entity graph simple).
 *
 * <p>The {@code matchedRules} field is stored as a separate collection table
 * ({@code fraud_alert_matched_rules}) using {@code @ElementCollection} with
 * {@code FetchType.EAGER} so that the rule names are always available without an additional
 * query — this list is typically small (2–4 entries at most) and is needed whenever an alert is
 * displayed.
 *
 * <p>The {@code ruleDetails} field stores the full JSON array of
 * {@link za.co.fraudruleengine.rule.RuleResult} objects, providing analysts with the
 * complete evidence picture including rules that did not fire.
 */
@Entity
@Table(name = "fraud_alerts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FraudAlertEntity {

    /** Unique identifier for this alert; generated by the application layer. */
    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;

    /** UUID of the transaction that triggered this alert; logical foreign key to {@code transactions}. */
    @Column(name = "transaction_id", nullable = false)
    private UUID transactionId;

    /** The customer account associated with the flagged transaction. */
    @Column(name = "account_id", nullable = false)
    private String accountId;

    /** The aggregate risk score at the time the alert was raised. */
    @Column(name = "total_risk_score", nullable = false)
    private int totalRiskScore;

    /**
     * The current lifecycle status of the alert.
     * Stored as its string name in the database (e.g. {@code "OPEN"}) to ensure
     * human-readability in SQL queries and avoid ordinal-ordering issues.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AlertStatus status;

    /**
     * The names of all fraud rules that matched this transaction.
     * Stored in the {@code fraud_alert_matched_rules} child table, fetched eagerly to
     * avoid lazy-loading issues when the entity is serialised outside of a transaction.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "fraud_alert_matched_rules",
            joinColumns = @JoinColumn(name = "alert_id"))
    @Column(name = "rule_name")
    private List<String> matchedRules;

    /**
     * JSON snapshot of all {@link za.co.fraudruleengine.rule.RuleResult} objects
     * (matching and non-matching) from the evaluation that triggered this alert.
     * Stored as {@code TEXT} to accommodate payloads of arbitrary length.
     */
    @Column(name = "rule_details", columnDefinition = "text")
    private String ruleDetails;

    /** Timestamp set automatically by Hibernate on first insert; never updated. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp updated automatically by Hibernate on every save, tracking the last status change. */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
